import type { Metadata } from "next";
import { Inter, Space_Mono, Space_Grotesk } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const space_grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
});

const space_mono = Space_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space_grotesk.variable} ${space_mono.variable} bg-[#f8f8f8]`}>
        {children}
      </body>
    </html>
  );
}
