import type { Metadata } from "next";
import {
  Roboto,
  Space_Mono,
  Space_Grotesk,
  Lexend_Deca,
} from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});

const space_grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
});

const space_mono = Space_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: "400",
});

const lexend_deca = Lexend_Deca({
  subsets: ["latin"],
  variable: "--font-deca",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space_grotesk.variable} ${space_mono.variable} bg-[#f8f8f8]`}>
        {children}
      </body>
    </html>
  );
}
